// frontend/src/views/Home/LandingPage.jsx
import React from "react";
// nodejs library that concatenates classes
import classNames from "classnames";
import { Link } from "react-router-dom";


// @material-ui/core components
import withStyles from "@material-ui/core/styles/withStyles";
import { Favorite, Star } from "@material-ui/icons";

// @material-ui/icons

// core components
import Header from "components/Header/Header.jsx";
import Footer from "components/Footer/Footer.jsx";
import GridContainer from "components/Grid/GridContainer.jsx";
import GridItem from "components/Grid/GridItem.jsx";
import Button from "components/CustomButtons/Button.jsx";
import HeaderLinks from "components/Header/HeaderLinks.jsx";
import Parallax from "components/Parallax/Parallax.jsx";

import landingPageStyle from "assets/jss/material-kit-react/views/landingPage.jsx";

// Sections for this page
const dashboardRoutes = [];

class LandingPage extends React.Component {
  render() {
    const { classes, ...rest } = this.props;
    return (
      <div>
        <Header
          color="dark"
          routes={dashboardRoutes}
          brand="Cultidate"
          rightLinks={<HeaderLinks />}
          fixed
          changeColorOnScroll={{
            height: 400,
            color: "white"
          }}
          {...rest}
        />
        <Parallax filter image={require("assets/img/land.jpg")}>
          <div className={classes.container}>
            <GridContainer>
              <GridItem xs={12} sm={12} md={6}>
                <h1 className={classes.title}>Cultidate</h1>
                <h4>
                  Cultidate is a social platform for cultural activities. You can create events, join other events, interact with the others, get event recommendations, create your own profile, add other users as friends and message them privately.
</h4>
                <br />

                <Button
                  color="danger"
                  round
                  size="lg"
                  href="/sign-up"
                  rel="noopener noreferrer"
                >
                  <i className="fas" /><Favorite />Sign Up
                </Button>
                <Button
                  color="danger"
                  round
                  size="lg"
                  href="/login"
                  rel="noopener noreferrer"
                >
                  <i className="fas" /><Star />Login
                </Button>
              </GridItem>
            </GridContainer>
          </div>
        </Parallax>
        <Footer />
      </div>
    );
  }
}

export default withStyles(landingPageStyle)(LandingPage);

// frontend/src/views/landing-page/index.vue
<template>
    <video-bg :sources="['src/assets/video/timelapse.mp4']" img="src/assets/video/bg.jpg">
    <div class=center-item>
        <h1 align="center">Cultidate</h1>
        <h3>Cultidate is a social platform for cultural activities. You can create events,
             join other events, interact with the others, get event recommendations, create 
             your own profile, add other users as friends and message them privately.</h3>
        <el-row class="center-button">
            <router-link to="/signup"><el-button round class="button-margin">Sign up</el-button></router-link>
            <router-link to="/login?redirect=%2Fdashboard"><el-button round class="button-margin">Login</el-button></router-link>
        </el-row>
        <el-steps :space="200" :active="4" finish-status="success" align-center>
            <el-step title="Find Cultidate" ></el-step>
            <el-step title="Sign Up"></el-step>
            <el-step title="Login"></el-step>
            <el-step title="Join Events!"></el-step>
        </el-steps>
        </div>
    </video-bg>
</template>

<script>
import VideoBg from 'vue-videobg'

export default {
  name: 'LandingPage',
  components: {
    VideoBg
  },
}
</script>

<style rel="stylesheet/scss" lang="scss" scoped>
.VideoBg {
  min-height: 640px;
}
.center-button{
    display: flex;
    justify-content: center;
}
.button-margin{
    margin: 20px;
}
.center-item{
  position: absolute;
    top: 50%;
    left: 50%;

    -moz-transform: translateX(-50%) translateY(-50%);
    -webkit-transform: translateX(-50%) translateY(-50%);
    transform: translateX(-50%) translateY(-50%);
}
.VideoBg__content {
  text-align: center;
  display: flex;
  justify-content: center;
  background-color: rgba(52, 72, 92, 0.7);
}

img {
  width: 200px;
  margin-top: 120px;
}
h1 {
  margin: 40px 0;
  font-family: 'Dosis', 'Source Sans Pro', 'Helvetica Neue', sans-serif;
  font-weight: 300;
  font-size: 4em;
  color: #ebebeb;
  text-shadow: 1px 1px rgb(184, 183, 180);

}

h3, a {
  font-family: 'Source Sans Pro', 'Helvetica Neue', sans-serif;
  font-weight: 400;
  text-shadow: 1px 1px rgb(184, 183, 180);

//   font-size: 15px;
  color: #ebebeb;
}
</style>
